// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6lX4Xdj4T_tBi2AkAPVQl5-jmc6Sgvx0',
    appId: '1:268509323713:web:f670cc3cfd41d8c4e4cf40',
    messagingSenderId: '268509323713',
    projectId: 'flutterproject-d5e9d',
    authDomain: 'flutterproject-d5e9d.firebaseapp.com',
    storageBucket: 'flutterproject-d5e9d.firebasestorage.app',
    measurementId: 'G-EW693503ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDotQzQbGhigG17l9d6vCRhvVt1wj80P24',
    appId: '1:268509323713:android:00a1fee8837e2a0ee4cf40',
    messagingSenderId: '268509323713',
    projectId: 'flutterproject-d5e9d',
    storageBucket: 'flutterproject-d5e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAgVI18YflttfZ3UW9KfmtDqoxfX0eSTg',
    appId: '1:268509323713:ios:8fb10e2f442a77b7e4cf40',
    messagingSenderId: '268509323713',
    projectId: 'flutterproject-d5e9d',
    storageBucket: 'flutterproject-d5e9d.firebasestorage.app',
    iosBundleId: 'com.example.lifeCountdown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAgVI18YflttfZ3UW9KfmtDqoxfX0eSTg',
    appId: '1:268509323713:ios:db5e62f325097e3be4cf40',
    messagingSenderId: '268509323713',
    projectId: 'flutterproject-d5e9d',
    storageBucket: 'flutterproject-d5e9d.firebasestorage.app',
    iosBundleId: 'com.example.lifeCountdown.RunnerTests',
  );
}
